export const options = [
  { label: "acorn squash ", value: "acorn squash " },
  { label: "alfalfa sprouts ", value: "alfalfa sprouts " },
  { label: "anise ", value: "anise " },
  { label: "artichoke ", value: "artichoke " },
  { label: "arugula ", value: "arugula " },
  { label: "asparagus ", value: "asparagus " },
  { label: "aubergine ", value: "aubergine " },
  { label: "azuki beans ", value: "azuki beans " },
  { label: "banana squash ", value: "banana squash " },
  { label: "basil ", value: "basil " },
  { label: "bean sprouts ", value: "bean sprouts " },
  { label: "beetroot ", value: "beetroot " },
  { label: "bell pepper ", value: "bell pepper " },
  { label: "bitter melon ", value: "bitter melon " },
  { label: "black beans ", value: "black beans " },
  { label: "black-eyed peas ", value: "black-eyed peas " },
  { label: "bok choy ", value: "bok choy " },
  { label: "borlotti bean ", value: "borlotti bean " },
  { label: "broad beans ", value: "broad beans " },
  { label: "broccoflower ", value: "broccoflower " },
  { label: "broccoli ", value: "broccoli " },
  { label: "brussels sprouts ", value: "brussels sprouts " },
  { label: "butter bean ", value: "butter bean " },
  { label: "butternut squash ", value: "butternut squash " },
  { label: "cabbage ", value: "cabbage " },
  { label: "caraway ", value: "caraway " },
  { label: "carrot ", value: "carrot " },
  { label: "cauliflower ", value: "cauliflower " },
  { label: "cayenne pepper ", value: "cayenne pepper " },
  { label: "ceci beans ", value: "ceci beans " },
  { label: "celeriac ", value: "celeriac " },
  { label: "celery ", value: "celery " },
  { label: "chamomile ", value: "chamomile " },
  { label: "chard ", value: "chard " },
  { label: "chickpeas ", value: "chickpeas " },
  { label: "chili pepper ", value: "chili pepper " },
  { label: "chives ", value: "chives " },
  { label: "collard greens ", value: "collard greens " },
  { label: "coriander ", value: "coriander " },
  { label: "corms ", value: "corms " },
  { label: "courgette ", value: "courgette " },
  { label: "cucumber ", value: "cucumber " },
  { label: "cymbopogon ", value: "cymbopogon " },
  { label: "daikon ", value: "daikon " },
  { label: "daikon or white radish ", value: "daikon or white radish " },
  { label: "delicata ", value: "delicata " },
  { label: "dill ", value: "dill " },
  { label: "eddoe ", value: "eddoe " },
  { label: "endive ", value: "endive " },
  { label: "fennel ", value: "fennel " },
  { label: "fennel ", value: "fennel " },
  { label: "fiddleheads ", value: "fiddleheads " },
  { label: "frisee ", value: "frisee " },
  { label: "garbanzos ", value: "garbanzos " },
  { label: "garlic ", value: "garlic " },
  { label: "gem squash ", value: "gem squash " },
  { label: "ginger ", value: "ginger " },
  { label: "green beans ", value: "green beans " },
  { label: "greens ", value: "greens " },
  { label: "habanero ", value: "habanero " },
  { label: "herbs ", value: "herbs " },
  { label: "horseradish ", value: "horseradish " },
  { label: "hubbard squash ", value: "hubbard squash " },
  { label: "jalape�o ", value: "jalape�o " },
  { label: "jerusalem artichoke ", value: "jerusalem artichoke " },
  { label: "jicama ", value: "jicama " },
  { label: "kale ", value: "kale " },
  { label: "kidney beans ", value: "kidney beans " },
  { label: "kohlrabi ", value: "kohlrabi " },
  { label: "konjac ", value: "konjac " },
  { label: "lavender ", value: "lavender " },
  { label: "leek ", value: "leek " },
  { label: "legumes ", value: "legumes " },
];
